[package]
name = "typ-datetime"
version = "0.1.0"
edition = "2021"

[dependencies]

serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_yaml = "~0"

chrono = { version = "~0", features = ["serde"] }
derive-new = "~0"